/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.theveganrobot.cvcamera.jni;

public interface cvcameraConstants {
  public final static int DETECT_FAST = cvcameraJNI.DETECT_FAST_get();
  public final static int DETECT_STAR = cvcameraJNI.DETECT_STAR_get();
  public final static int DETECT_SURF = cvcameraJNI.DETECT_SURF_get();
}
